--- !ditz.rubyforge.org,2008-03-06/project 
name: milpon
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: milpon
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: beta7
  status: :released
  release_time: 2009-04-16 10:55:31.745662 Z
  log_events: 
  - - 2009-02-01 09:20:12.222331 Z
    - mootoh <mootoh@gmail.com>
    - created
    - UI improvements.
  - - 2009-04-16 10:55:31.745696 Z
    - mootoh <mootoh@gmail.com>
    - released
    - released to beta testers.
- !ditz.rubyforge.org,2008-03-06/release 
  name: revised AddTask view
  status: :released
  release_time: 2009-03-11 07:49:13.989073 Z
  log_events: 
  - - 2009-02-19 12:41:22.568741 Z
    - mootoh <mootoh@gmail.com>
    - created
    - more user-friendly view for adding a task.
  - - 2009-03-11 07:49:13.989109 Z
    - mootoh <mootoh@gmail.com>
    - released
    - finished!
- !ditz.rubyforge.org,2008-03-06/release 
  name: new ui
  status: :released
  release_time: 2009-04-16 10:57:23.797913 Z
  log_events: 
  - - 2009-03-09 01:10:27.308850 Z
    - mootoh <mootoh@gmail.com>
    - created
    - UI renewal
  - - 2009-04-16 10:57:23.797936 Z
    - mootoh <mootoh@gmail.com>
    - released
    - drop it.
- !ditz.rubyforge.org,2008-03-06/release 
  name: beta08
  status: :released
  release_time: 2009-05-16 03:40:18.147085 Z
  log_events: 
  - - 2009-04-16 10:53:15.156761 Z
    - mootoh <mootoh@gmail.com>
    - created
    - ""
  - - 2009-05-16 03:40:18.147100 Z
    - mootoh <mootoh@gmail.com>
    - released
    - released!
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.1"
  status: :released
  release_time: 2009-05-21 16:18:03.147896 Z
  log_events: 
  - - 2009-04-16 10:58:28.117185 Z
    - mootoh <mootoh@gmail.com>
    - created
    - new UI, tag support.
  - - 2009-05-21 16:18:03.147921 Z
    - mootoh <mootoh@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "2.1"
  status: :released
  release_time: 2009-08-11 10:56:52.462455 Z
  log_events: 
  - - 2009-05-21 16:17:18.996697 Z
    - mootoh <mootoh@gmail.com>
    - created
    - minor improvements and bug fixes from 2.0.
  - - 2009-08-11 10:56:52.462527 Z
    - mootoh <mootoh@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "2.2"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-08-11 10:55:43.079468 Z
    - mootoh <mootoh@gmail.com>
    - created
    - Improve the usability.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "2.3"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-09-29 02:28:19.638634 Z
    - Takayama Motohiro <mootoh@gmail.com>
    - created
    - background sync.
