--- !ditz.rubyforge.org,2008-03-06/project 
name: milpon
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: milpon
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: beta7
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-02-01 09:20:12.222331 Z
    - mootoh <mootoh@gmail.com>
    - created
    - UI improvements.
- !ditz.rubyforge.org,2008-03-06/release 
  name: revised AddTask view
  status: :released
  release_time: 2009-03-11 07:49:13.989073 Z
  log_events: 
  - - 2009-02-19 12:41:22.568741 Z
    - mootoh <mootoh@gmail.com>
    - created
    - more user-friendly view for adding a task.
  - - 2009-03-11 07:49:13.989109 Z
    - mootoh <mootoh@gmail.com>
    - released
    - finished!
- !ditz.rubyforge.org,2008-03-06/release 
  name: new ui
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-03-09 01:10:27.308850 Z
    - mootoh <mootoh@gmail.com>
    - created
    - UI renewal
